import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  JoinColumn,
  ManyToOne,
  PrimaryColumn,
} from 'typeorm';
import { User } from '../../users/entities/user.entity';

/** One row per login (device). Its id is the `sid` claim in both JWTs. */
@Entity('sessions')
@Index('ix_sessions_user', ['userId'], { where: '"revoked_at" IS NULL' })
export class Session {
  /** Generated by the app so the refresh token can carry it before insert. */
  @PrimaryColumn({ type: 'uuid', primaryKeyConstraintName: 'pk_sessions' })
  id: string;

  @ManyToOne(() => User, { onDelete: 'CASCADE', nullable: false })
  @JoinColumn({ name: 'user_id', foreignKeyConstraintName: 'fk_sessions_user' })
  user: User;

  @Column({ name: 'user_id', type: 'uuid' })
  userId: string;

  /** SHA-256 of the current refresh token. */
  @Column({
    name: 'refresh_token_hash',
    type: 'varchar',
    length: 64,
    select: false,
  })
  refreshTokenHash: string;

  @Column({ name: 'user_agent', type: 'varchar', length: 500, nullable: true })
  userAgent: string | null;

  @Column({ name: 'ip_address', type: 'varchar', length: 64, nullable: true })
  ipAddress: string | null;

  @Column({ name: 'expires_at', type: 'timestamptz' })
  expiresAt: Date;

  /** null = active */
  @Column({ name: 'revoked_at', type: 'timestamptz', nullable: true })
  revokedAt: Date | null;

  @CreateDateColumn({ name: 'created_at', type: 'timestamptz' })
  createdAt: Date;
}
