/** Machine-readable error codes returned in every error body (PRD §7). */
export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_REUSED = 'REFRESH_TOKEN_REUSED',
  FORBIDDEN = 'FORBIDDEN',
  ACCOUNT_DISABLED = 'ACCOUNT_DISABLED',
  NOT_FOUND = 'NOT_FOUND',
  EMAIL_TAKEN = 'EMAIL_TAKEN',
  ALREADY_ON_PLAN = 'ALREADY_ON_PLAN',
  PROVIDER_IS_DEFAULT = 'PROVIDER_IS_DEFAULT',
  PROVIDER_DISABLED = 'PROVIDER_DISABLED',
  LAST_ADMIN = 'LAST_ADMIN',
  USAGE_LIMIT_EXCEEDED = 'USAGE_LIMIT_EXCEEDED',
  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  PROVIDER_ERROR = 'PROVIDER_ERROR',
  PROVIDER_TIMEOUT = 'PROVIDER_TIMEOUT',
  // added where PRD §7 has no code (docs/DECISIONS.md)
  PROVIDER_NAME_TAKEN = 'PROVIDER_NAME_TAKEN',
}
